GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "oskat",
    "email": "os@gmail.com",
    "password": "12345o"
}


###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "inputEmail": "test@gmail.com",
    "inputPassword": "12345"
}






